% floory
global fig;

fig = openfig('frontend.fig');

% Initiera GUI
handles = guihandles(fig);
set(handles.connectbutton, 'Visible', 'on');
set(handles.disconnectbutton, 'Visible', 'off');
guidata(fig, handles);

% Initiera default-värden
global incoming_bytes;
global incoming_index;
global history;
global history_index;
global recieve_in_progress;
global got_ack;
global sending_config;
global recieve_count;
global lh_front;
global lh_right;
global lh_left;
global lh_gyro;
global lh_tejp;
global lb;

incoming_bytes = zeros(1,18);
incoming_index = 1;
recieve_count = 1;
sending_config = 0;
recieve_in_progress = 0;
got_ack = 1;

history = zeros(10000, 18);
history_index = 1;



% Förbered plotten
axes('xlim',[1,length(history)],'ylim',[0,200]);
x=1:length(history);
y=-inf*ones(size(x));
lh_front=line(x,y,...
    'userdata',1,...
    'marker','.',...
    'markersize',5,...
    'linestyle','none',...
    'color', 'r');
lh_right=line(x,y,...
    'userdata',1,...
    'marker','.',...
    'markersize',5,...
    'linestyle','none',...
    'color', 'g');
lh_left=line(x,y,...
    'userdata',1,...
    'marker','.',...
    'markersize',5,...
    'linestyle','none',...
    'color', 'b');
lh_tejp=line(x,y,...
    'userdata',1,...
    'marker','.',...
    'markersize',5,...
    'linestyle','none',...
    'color', 'k');
lh_gyro=line(x,y,...
    'userdata',1,...
    'marker','.',...
    'markersize',5,...
    'linestyle','none',...
    'color', 'c');
lb=line([inf,inf],[0,200]);
shg;
