function realtime_plot
    global history;
    global lh_front;
    global lh_right;
    global lh_left;
    global lh_gyro;
    global lh_tejp;
    global lb;
    global realtime_plot_enabled;
    
    figure(2);

    % Förbered plotten
    axes('xlim',[1,length(history)],'ylim',[0,200]);
    x=1:length(history);
    y=-inf*ones(size(x));
    lh_front=line(x,y,...
        'userdata',1,...
        'marker','.',...
        'markersize',5,...
        'linestyle','none',...
        'color', 'r');
    lh_right=line(x,y,...
        'userdata',1,...
        'marker','.',...
        'markersize',5,...
        'linestyle','none',...
        'color', 'g');
    lh_left=line(x,y,...
        'userdata',1,...
        'marker','.',...
        'markersize',5,...
        'linestyle','none',...
        'color', 'b');
    lh_tejp=line(x,y,...
        'userdata',1,...
        'marker','.',...
        'markersize',5,...
        'linestyle','none',...
        'color', 'k');
    lh_gyro=line(x,y,...
        'userdata',1,...
        'marker','.',...
        'markersize',5,...
        'linestyle','none',...
        'color', 'c');
    lb=line([inf,inf],[0,200]);
    shg;
    
    realtime_plot_enabled = true;
end